### ISSUE TITLE
Regex breaks syntax highlighting

### ISSUE THREAD

**Issue by cPsYcRoW** [bef/atom-language-tcltk#1]
Hi,
Firstly, thank-you so much for improving the zpconn version of this textmate conversion. We use this language exclusively at our office and it is a pain as it is hardly known or supported. I appreciate the work you have done to make this more usable in Atom.

I have an issue where Regex breaks the syntax highlighting. I actually logged this as an issue in the zpconn version with an example. I hope this can be fixed.

Do you have any idea how one could get the symbols working correctly for TCL in Atom (CTRL+R). It seems to only support namespaces and procs. It would be great if it could also support snit and TCLOO. It would be such a timesaver to hit a hotkey and see a list of methods in the current file you are working in. Actually, being able to goto a definition would be brilliant. I am probably asking too much.

Hope you at least get to read this.

**Comment by bef** [comment]
Hi cPsYcRoW,
thank you for your feedback. Can you provide a link to the zpconn issue with an example?

Support for snit, tcloo, goto def, ... would indeed be nice to have. If you happen to have some atom code already, feel free to send a pull request.

**Comment by cPsYcRoW** [comment]
[tcl.cson..zip](https://github.com/bef/atom-language-tcltk/files/256590/tcl.cson.zip)

Hi,

Ok, this snippet of code breaks syntax highlighting for me. Just pop it in
between some existing code.

```
if { (! $FLAGS(blah)) && ([regexp -- {=\d{4}=} $T(blah)] > 0) } {
  lappend constraints "unsupported-bar"
}
```

I have attempted to update the tcl.cson file to support TCL OO and snit. It
doesn't seem to be working though, although the equivalent code does work
in Sublime Text 3. I have probably done something silly. I am quite busy
with a project though so I thought i would attach the file anyway.

Let me know if this helps you at all.

Thanks

**Comment by bef** [comment]
regex should be fine now.
The `--` end of options switch is not handled correctly, but calls such as `regexp -a -b -- -c` are misleading anyway and should be rewritten as `... {-c}`.

As for your feature requests, I will take a look at your attachment.
